spring:
  application:
    name: multiDatasource

  datasource:
    dbone:
      url: jdbc:mysql://172.17.10.83:3306/dbone?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    dbtwo:
      url: jdbc:mysql://172.17.10.83:3306/dbtwo?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
    dbthree:
      url: jdbc:mysql://172.17.10.83:3306/dbthree?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      maxActive: 100
      minIdle: 5
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 30
      filters: stat